<a href="https://colab.research.google.com/github/HyeongChanHam/datamining/blob/master/assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
vm = [26.7, 26.9, 27.6, 26.9, 27.2, 27.0, 26.2]
cbi = [1.14, 1.41, 1.13, 1.37, 1.14, 1.26, 1.28]
di = [87.8, 87.0, 88.0, 87.1, 87.9, 87.0, 88.0]

df = {'vm':vm, 'cbi':cbi, 'di':di}

In [0]:
np.array()

In [0]:
df = pd.DataFrame(df)

In [0]:
y = df['di']
x = df[df.columns[0:2]]

In [0]:
import numpy as np

In [0]:
one = np.array([1 for _ in range(7)])

In [29]:
print(one)
print(np.transpose(one))
print(one.reshape(-1,))

[1 1 1 1 1 1 1]
[1 1 1 1 1 1 1]
[1 1 1 1 1 1 1]


In [0]:
o = pd.DataFrame(one)

In [0]:
x = pd.concat([o, x], axis=1)

In [72]:
x = x.values



AttributeError: ignored

In [73]:
y

0    87.8
1    87.0
2    88.0
3    87.1
4    87.9
5    87.0
6    88.0
Name: di, dtype: float64

In [76]:
np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)

array([102.5419763 ,  -0.38347545,  -3.7467023 ])

In [78]:
np.linalg.inv(x.T.dot(x))

array([[888.41039039, -30.24486693, -59.18846697],
       [-30.24486693,   1.05299588,   1.51481626],
       [-59.18846697,   1.51481626,  14.75101981]])

In [58]:
i = pd.DataFrame(np.linalg.inv(x.T.dot(x)))
i.dot(x.T)

ValueError: ignored

In [94]:
y_s = y-y.mean()
# y_s = np.array(y_s)
np.square(y_s).sum()/(len(y_s)-1)

0.23285714285714412

In [97]:
np.sqrt(np.square(y_s).sum()/(len(y_s)-1))

0.4825527358301309

In [102]:
np.sqrt(14.751) * 0.4826

1.8535232970642692